"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EDRGGSIDropPodState = void 0;
var EDRGGSIDropPodState;
(function (EDRGGSIDropPodState) {
    EDRGGSIDropPodState[EDRGGSIDropPodState["Dropping"] = 0] = "Dropping";
    EDRGGSIDropPodState[EDRGGSIDropPodState["Drilling"] = 1] = "Drilling";
    EDRGGSIDropPodState[EDRGGSIDropPodState["Landed"] = 2] = "Landed";
    EDRGGSIDropPodState[EDRGGSIDropPodState["PrepTakeoff"] = 3] = "PrepTakeoff";
    EDRGGSIDropPodState[EDRGGSIDropPodState["Departing"] = 4] = "Departing";
    EDRGGSIDropPodState[EDRGGSIDropPodState["WaitingForGameStart"] = 5] = "WaitingForGameStart";
    EDRGGSIDropPodState[EDRGGSIDropPodState["InSpace"] = 6] = "InSpace";
    EDRGGSIDropPodState[EDRGGSIDropPodState["Destroy"] = 7] = "Destroy";
    EDRGGSIDropPodState[EDRGGSIDropPodState["WaitOnSpacerig"] = 8] = "WaitOnSpacerig";
    EDRGGSIDropPodState[EDRGGSIDropPodState["ExitSpacerig"] = 9] = "ExitSpacerig";
    EDRGGSIDropPodState[EDRGGSIDropPodState["Damaged"] = 10] = "Damaged";
    EDRGGSIDropPodState[EDRGGSIDropPodState["PoweringUp"] = 11] = "PoweringUp";
    EDRGGSIDropPodState[EDRGGSIDropPodState["PoweredUp"] = 12] = "PoweredUp";
    EDRGGSIDropPodState[EDRGGSIDropPodState["DeepDiveDeparture"] = 13] = "DeepDiveDeparture";
})(EDRGGSIDropPodState || (EDRGGSIDropPodState = {}));
exports.EDRGGSIDropPodState = EDRGGSIDropPodState;
